// THE STRIP'S OWN PAINT — the active tab's underline, the Code view's syntax
// colours, and the pane of glass the editor is — shipped WITH the display.
//
// WHY THIS FILE EXISTS. A host builds its stylesheet by SCANNING SOURCE for
// utility classes, and this package's source is not in the trees a host scans:
// an installed package sits outside them, and a linked development clone sits
// in a path the host's own ignore rules exclude. A utility class used only here
// is therefore never generated — the class attribute is written, the element is
// in the page, and no rule exists. Nothing errors; the paint is simply absent.
// So the paint this chrome cannot do without lands from here.
//
// ONLY THE NEW CHROME. The rendered post keeps the body treatment it already
// had; nothing below touches it. The three things that could not be left to a
// utility class are the active tab's 2px underline (the application spells that
// class behind a state variant, so the plain form is generated by nobody), the
// code view's token colours (arbitrary values no other file uses), and the
// editor's transparency (the application's control ground is an UNLAYERED rule
// and beats every layered utility, so the textarea would take that ground as an
// opaque sheet over the highlighted text).
//
// EVERY SELECTOR IS SCOPED TO THIS DISPLAY, and that is not decoration. A style
// element styles the WHOLE DOCUMENT, not the subtree it sits in — so a rule
// written for this display alone would otherwise have reached any element
// anywhere on the page, host or third party. The display's own root carries
// `data-artifact-renderer="blog-post"`, so every rule below begins there.
//
// NO COLOUR IS WRITTEN HERE. Every one is a named application custom property,
// so this display follows the theme in light and dark without knowing which is
// on; where a token may be absent (a display drawn inside a third-party
// application that declares fewer of them) the fallback is `currentColor`,
// never an invented colour. `--primary` and `--accent` are deliberately NOT
// used: the application aliases them to a near-white slate in its dark theme,
// so the strip's indigo is `--info`, which is declared in its own right in both.

import type { ReactElement } from "react";

export const TEXT_DISPLAY_CSS = `
[data-artifact-renderer="blog-post"] [role="tab"] {
  position: relative;
}
[data-artifact-renderer="blog-post"] [role="tab"][data-active="true"] {
  color: var(--info, currentColor);
}
[data-artifact-renderer="blog-post"] [role="tab"][data-active="true"]::after {
  content: "";
  position: absolute;
  inset-inline: 0;
  bottom: -1px;
  height: 2px;
  background: var(--info, currentColor);
  pointer-events: none;
}

[data-artifact-renderer="blog-post"] [data-token] {
  color: var(--foreground, currentColor);
}
[data-artifact-renderer="blog-post"] [data-token="heading"] {
  color: var(--info, currentColor);
  font-weight: 600;
}
[data-artifact-renderer="blog-post"] [data-token="code"] {
  color: var(--warning, currentColor);
}
[data-artifact-renderer="blog-post"] [data-token="link"] {
  color: var(--success, currentColor);
}
[data-artifact-renderer="blog-post"] [data-token="strong"] {
  font-weight: 700;
}
[data-artifact-renderer="blog-post"] [data-token="emphasis"] {
  color: var(--destructive, currentColor);
  font-style: italic;
}
[data-artifact-renderer="blog-post"] [data-token="marker"] {
  color: var(--muted-foreground, currentColor);
}

[data-artifact-renderer="blog-post"] textarea[data-code-editor]:not([data-slot="input-group-control"]) {
  background: transparent;
  box-shadow: none;
  color: transparent;
  -webkit-text-fill-color: transparent;
}
[data-artifact-renderer="blog-post"] textarea[data-code-editor]::selection {
  color: var(--foreground, currentColor);
  -webkit-text-fill-color: var(--foreground, currentColor);
}
`;

/**
 * The stylesheet, mounted with the display.
 *
 * Drawn inside the display's own element rather than hoisted to the document,
 * so a host that mounts one display, ten displays or none carries exactly the
 * rules its page needs and nothing outlives the component. ONCE PER DISPLAY:
 * the strip's root mounts it, and the parts beneath it never mount it again.
 */
export function TextDisplayStyle(): ReactElement {
  return <style>{TEXT_DISPLAY_CSS}</style>;
}
